### ISSUE TITLE
Plan for 0.1.0

### ISSUE THREAD

**Issue by Kertoo** [ncn-foreigners/singleRcaptureExtra#1]
Planned features for 0.1.0 version of this package

Count data model estimation `estimatePopsize` method for:
- `vgam` class
  - [x] Basic functionality, derivatives, pop est, etc.
  - [x] Bootstraping
  - [x] Methods
  - [x] Controls
  - [ ] Post-hoc methods
- `vglm` class
  - [x] Basic functionality, derivatives, pop est, etc.
  - [x] Bootstraping
  - [x] Methods
  - [x] Controls
  - [ ] Post-hoc methods
- `zerotrunc` class
  - [x] Basic functionality, derivatives, pop est, etc.
  - [x] Bootstraping
  - [x] Methods
  - [x] Controls
  - [ ] Post-hoc methods

List of methods:
- dfpopsize
- plot
- nobs
- simulate
- stratifyPopsize
- marginalFreq
- Other general methods where we just pass foreign object e.g. `AIC(object)=AIC(object$foreignObject)`

Maybe's (??):
- [ ] Make `VGAM` family functions for distributions from `singleRcapture`
- [ ] ...

Ratio regression model estimation `estimatePopsize` method for:
- `vgam` class
  - [ ] Basic functionality, derivatives, pop est, etc.
  - [ ] Bootstraping
  - [ ] Methods
  - [ ] Controls
  - [ ] Post-hoc methods
- `vglm` class
  - [ ] Basic functionality, derivatives, pop est, etc.
  - [ ] Bootstraping
  - [ ] Methods
  - [ ] Controls
  - [ ] Post-hoc methods
- `glm` class
  - [ ] Basic functionality, derivatives, pop est, etc.
  - [ ] Bootstraping
  - [ ] Methods
  - [ ] Controls
  - [ ] Post-hoc methods
- `lm` class
  - [ ] Basic functionality, derivatives, pop est, etc.
  - [ ] Bootstraping
  - [ ] Methods
  - [ ] Controls
  - [ ] Post-hoc methods

- [x] Wait for `singleRcapture` 0.2.1 to be on CRAN :)

**Comment by Kertoo** [comment]
@BERENZ if you think anything is missing from this roadmap feel free to edit original comment
